### ISSUE TITLE
Cross Session Thought Contamination

### ISSUE THREAD

**Issue by ajbarnes** [VT-CHCI/Thought-Swap#21] opened 2015-02-17 18:24 UTC
Thoughts from 1 session appear in the next after 'new session' is pressed

**Comment by hcientist** [comment] 2015-02-17 18:25
also i see this error in the server log when "thought contamination" occurs 

```
logDistribute error:
{ [Error: ER_NO_REFERENCED_ROW_: Cannot add or update a child row: a foreign key constraint fails (`thoughtswap`.`thoughtswap_events`, CONSTRAINT `fk_events_distributions1` FOREIGN KEY (`distribution_id`) REFERENCES `thoughtswap_distributions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)]
  code: 'ER_NO_REFERENCED_ROW_',
  errno: 1452,
  sqlState: '23000',
  index: 0 }
```

**Comment by hcientist** [comment] 2015-02-17 19:35
duplicate of #13

**Closed as completed by hcientist** 2015-02-17 19:35 UTC
